#!/bin/bash

if test -r output/graph.dat ; then
	rm output/graph.dat
fi

for i in 4 9 16 25 36 49 64 81 100 ; do 
	./PICellerator $@ --particleCount=$i > /dev/null
	cat output/output.dat >> output/graph.dat
	cat output/output.dat
done
