FROM underworldcode/petsc4py:3.11.2-slim

USER root

WORKDIR /tmp/jupyterhub-build
RUN apt-get update -qq && \
    curl -sL https://deb.nodesource.com/setup_12.x | bash - && \
    DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends \
        curl \
        git \
        m4 \
        ruby \
        texinfo \
        libbz2-dev \
        libcurl4-openssl-dev \
        libexpat-dev \
        libncurses-dev \
        zlib1g-dev \
        nodejs && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN npm install -g configurable-http-proxy && \
    git clone https://github.com/jupyterhub/jupyterhub.git && \
    cd jupyterhub && \
    python3 -m pip install --no-cache-dir -r requirements.txt && \
    python3 -m pip install --no-cache-dir . && \
    cd /tmp && \
    rm -rf *

RUN mkdir -p /srv/jupyterhub/
WORKDIR /srv/jupyterhub/
EXPOSE 8000

USER jovyan

LABEL org.jupyter.service="jupyterhub"

CMD ["jupyterhub"]