[workspace]
authors = ["Julian Giordani <julian.giordani@sydney.edu.au>"]
channels = [
  "conda-forge",
  "https://prefix.dev/pixi-build-backends"
]
name = "uw2-pixi"
platforms = ["linux-64", "osx-arm64"]

[tasks]
build = "pip install ."
test = "pytest ./docs/pytests/tests.py ./docs/pytests/test_examples.py ./docs/pytests/test_user_guide.py"

[dependencies]
petsc = "3.21.*"
python = "3.11.*"
numpy = "<2"
pint = ">=0.24.4,<0.25"
cmake = ">=4.0.3,<5"
swig = ">=4"
pkg-config = ">=0.29.2,<0.30"
compilers = ">=1.10.0,<2"
scipy = ">=1.16.0,<2"
mpi4py = ">=4.1.0,<5"
libxml2 = ">=2.13.8,<3"
ninja = ">=1.13.0,<2"
mesalib = ">=25.0.5,<26"
mpich = ">=4.3.1,<5"
hdf5 = { version = "*", build = "mpi*" }
h5py = { version = "*", build = "mpi*" }
pip = ">=25.1.1,<26"
pytest = ">=8.4.1,<9"
nbmake = ">=1.5.5,<2"
jupytext = ">=1.17.2,<2"
jupyterlab = ">=4.4.4,<5"
matplotlib = ">=3.10.5,<4"
#[host-dependencies]
c-compiler = "*"
cxx-compiler = "*"
make = "*"
