name: uw-2.17
channels:
  - conda-forge
dependencies:
  - python==3.12
  - numpy<2
  - compilers
  - pkg-config
  - libxml2-devel
  - make
  - cmake
  - swig>=4.0.0
  - ninja
  - pint
  - mpich
  - petsc==3.21.5
  - mesalib
  - git
  - git-lfs
  - scipy
  - mpi4py
  - h5py=*=mpi*
  - pytest
  - nbmake
  - matplotlib
  - jupyterhub-singleuser
  - jupyterlab
  - jupytext
  - pip
  - pip:
    - lavavu
    - lavavu-osmesa
    #- badlands comment out for the following for now
    - "badlands @ git+https://github.com/julesghub/badlands.git@julesghub/meson-build#subdirectory=badlands"

