{% set name = "underworld2" %}
{% set version = "2.10.0b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../.

build:
  skip: true  # [win]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv 
  missing_dso_whitelist:
    - libm.so.6 
    - libc.so.6 

requirements:

  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ mpi }}

  host:
    - pkg-config
    - pip
    - python
    - libxml2
    - numpy>=1.18
    - cmake
    - swig>=4.0.0
    - ninja
    - petsc {{ petsc }}
    - {{ mpi }}

  run:
    - python
    - {{ mpi }}
    - numpy
    - petsc
    - pint
    - scipy
    - mpi4py
    - h5py

test:
  requires:
    - pytest
    - matplotlib

  source_files:
    - docs/pytests
    - docs/user_guide
    - docs/examples

  commands:
    - python -X faulthandler -c "import underworld; underworld.mesh.FeMesh_Cartesian();"
    - pytest -vvv docs/pytests


about:
  home: "https://github.com/underworldcode/underworld2"
  license: LGPL-3.0-only
  license_family: LGPL
  license_file:  LGPLv3.txt
  summary: "Geodynamics API"
  doc_url: https://underworld2.readthedocs.io
  dev_url: https://github.com/underworldcode/underworld2/tree/development

extra:
  recipe-maintainers:
    - rbeucher
    - jmansour
    - jgiordani
    - lmoresi
