#!/bin/sh

# Builds and watches the current directory
# Starts a web server at the _site directory

set -e
cd $(dirname "$0")/..

# We want to start the server from the _site directory
# where everything was built by the docker-site-builder script

cd _site

jupyter notebook --port=8080 --ip=0.0.0.0 --no-browser --NotebookApp.default_url="/files/Content/index.html"
