name: Underworld Install

on:
  push:
    branch:
      - new_ci

jobs:
  pip_install:
    runs-on: ubuntu-latest
    steps:
      - name: Install MPICH
        run: sudo apt-get install mpich
      
      - name: Install mpi4py
        run: pip install mpi4py

      - name: Install PETSc
        run: | 
          PETSC_CONFIGURE_OPTIONS='
                --with-debugging=0 \
                --COPTFLAGS="-g -O3" --CXXOPTFLAGS="-g -O3" --FOPTFLAGS="-g -O3" \
                --with-zlib=1                   \
                --download-hdf5=1               \
                --download-mumps=1              \
                --download-parmetis=1           \
                --download-metis=1              \
                --download-superlu=1            \
                --download-hypre=1              \
                --download-scalapack=1          \
                --download-superlu_dist=1       \
                --useThreads=0                  \
                --download-superlu=1            \
                --with-shared-libraries         \
                --with-cxx-dialect=C++11        \
                --with-make-np=8'
          export PETSC_CONFIGURE_OPTIONS
          pip install petsc

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Underworld
        run: pip install -vvv .
        


