name: Conda Test Environment, with micromamba

on:
  push:
    branches:
      - main
      - development
      - v2.*
  pull_request:
    branches:
      - '**'
  workflow_dispatch:
  
jobs:
  test:
    runs-on: [ubuntu-latest] #, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Micromamba
        uses: mamba-org/setup-micromamba@v3
        with:
          environment-file: conda/environment.yml
          environment-name: uw-2.17
          generate-run-shell: true
          cache-environment: true
          #cache-downloads: false

      - name: compile and pytests
        run: | 
          micromamba env list 
          micromamba list -v
          env
          pip install git+https://github.com/kinnala/meshplex
          pip install . --no-build-isolation
          pytest ./docs/pytests/tests.py ./docs/pytests/test_examples.py ./docs/pytests/test_UWGeo_examples.py
        shell: micromamba-shell {0}
