name: Conda Deploy

on: 
  release:
  workflow_dispatch:

jobs:
  conda_build:
    name: Conda Build (Python ${{matrix.python-version}} ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"] #, "macos-latest"] disable for now
        python-version: ["3.9", "3.10"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v3
        with:
          channels: conda-forge,defaults
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      - name: Config Conda
        shell: bash -el {0}
        run: |
            conda install --channel conda-forge conda-build anaconda-client conda-verify
            conda config --add channels conda-forge
            conda config --add channels underworldcode
            conda config --set anaconda_upload no
            anaconda logout

      - name: Config Conda For Upload
        if: github.event_name == 'release'
        shell: bash -el {0}
        run: conda config --set anaconda_upload yes

      - name: Upload new conda package
        if: github.event_name == 'release'
        shell: bash -el {0}
        run: |
            conda info
            anaconda login --hostname github-actions-${{ matrix.os  }}-$RANDOM --username ${{ secrets.ANACONDA_USERNAME }} --password ${{ secrets.ANACONDA_PASSWORD }}
            conda-build --channel conda-forge --user geo-down-under conda
            anaconda logout
