name: Conda Test Environment, with micromamba

on:
  push:
    branches:
      - main
      - development
      - v2.*
  pull_request:
    branches:
      - '**'
  workflow_dispatch:
  
jobs:
  test:
    runs-on: [ubuntu-latest] #, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: conda/environment.yaml
          generate-run-shell: true
          #environment-name: uw-2.17
          # persist only for runs on this commit.
          cache-environment-key: environment-${{ github.sha }}
          cache-downloads-key: downloads-${{ github.sha }}
          #cache-environment: true
          #cache-downloads: true
          
      - run: |
          mamba env list
          mamba list
          pip list
          mamba info
          pip install . --no-build-isolation
          #pytest ./docs/pytests/tests.py ./docs/pytests/test_examples.py
        shell: micromamba-shell {0}
# name: Compile the code, run tests
        
