name: Monthly issue metrics - Underworld
on:
  workflow_dispatch:
  schedule:
    - cron: "30 22 25 * *" # 22:30 on the 25th every month
    
permissions:
  contents: read

jobs:
  build:
    name: issue metrics
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: read
    steps:
      - name: Get dates for last month
        shell: bash
        run: |
          # Calculate the first day of the previous month
          first_day=$(date -d "last month" +%Y-%m-01)

          # Calculate the last day of the previous month
          last_day=$(date -d "$first_day +1 month -1 day" +%Y-%m-%d)

          #Set an environment variable with the date range
          echo "$first_day..$last_day"
          echo "last_month=$first_day..$last_day" >> "$GITHUB_ENV"

      - name: Run issue-metrics tool
        uses: github-community-projects/issue-metrics@v4
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SEARCH_QUERY: 'repo:underworldcode/underworld2 repo:underworldcode/underworld3 is:issue created:${{ env.last_month }} -reason:"not planned"'

      - name: Create issue
        uses: peter-evans/create-issue-from-file@v6
        with:
          title: Monthly issue metrics report
          token: ${{ secrets.GH_TOKEN }}
          content-filepath: ./issue_metrics.md
          assignees: julesghub
