name: Docker container on Kaiju

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Global Protect
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect
        uses: "./actions/globalprotect"
        env:
          USER: ${{ secrets.GB_USER }}
          PASS: ${{ secrets.GB_PASSWORD }}
          SERVER: ${{ secrets.GB_SERVER }}
          KAIJUPASSWD: ${{secrets.KAIJU_PASSWORD}}
          KAIJUUSER: ${{secrets.KAIJU_USERNAME}}

